version: '3.7'

services:
  x-app:
    # platform base on current system will be much faster
    build:
      context: ../../
      dockerfile: docker/Dockerfile
    image: ${APP_NAME}-${NODE_ENV}:${TAG}
    env_file:
      - .env
    restart: always
    ports:
      - '${DOCKER_HOST_PORT}:${DOCKER_CONTAINER_PORT}'
